### PR TITLE
Sonoff Dual R2 Example

### PR DESCRIPTION
**Pull request by lzparkma**
Implemented example for Sonoff Dual R2. Illustrates use of multiple homekit characteristics per device i.e. two switches per unit. Note that Button.c also modified to include additional event.

### CODE REVIEW

**Comment by maximkulkin** [comment]
@lzparkma Sorry for forgetting about this PR. Is it still up to date? I see that sonoff_basic_pwm was merged already.

**Comment by lzparkma** [comment]
Yes.

Matt

**Comment by maximkulkin** [comment]
Well, thing is that I see a long list of commits which changes are already been merged (via other PR), although they were squashed during merge and thus they still show up as new commits. I would prefer to also squash this PR into a single commit.
There is always a dilemma: I understand that this is open source and you might get annoyed by pesky repository owner nitpicking. I can do all massaging myself, but in that case all those commits will be under my name and it might be that you want to develop your own profile.
So, let me know whichever works for you: can you (or do you want to) rebase and squash code yourself or you only care about sharing code with others?

**Comment by lzparkma** [comment]
OK, rather astoundingly I think I might have been able to achieved the desired effect regarding rebasing commits. I still don't understand why it still wants to update files already added to your master. I assume this has something todo with committing all changes since I forked your master.

**Comment by royfocker19** [comment]
Hi Quick question, what is the view of the accessory for this dual lamp? is a rotary switch or there are to slicers on the same screen?

**Comment by lzparkma** [comment]
In this example it results in two separate switches with different names (which you can combine into a group in the iOS app). However, this was not by design I simply copy and pasted the characteristic and thus both had the primary=true flag (main.c lines 223 + 228). Not sure what happens is only one is primary like Maxim's sonoff_dual_lights example (main.c line 208 + 113).

**Comment by royfocker19** [comment]
Yes, 2 switches. After a power outage the device was not responding. Is it posible to delay the connection to ssid to give the connection more time to be available? Or is it any way to have a different button to just make a soft reset, not configuration reset.

**Comment by royfocker19** [comment]
Also, is there a way to avoid the relays to switch when the sonoff is starting?

**Comment by RavenSystem** [comment]
To give more time to connect to your known wifi, you can define WIFI_CONFIG_CONNECT_TIMEOUT with a greater value (default is 15000 = 15secs). For example, to give a 60 secs wifi timeout, you can compile with this flag:
`-DWIFI_CONFIG_CONNECT_TIMEOUT=60000`
After 60 secs without connecting to wifi network, Sonoff will go into AP mode to reconfigure its wifi.

**Comment by royfocker19** [comment]
Yes, I saw it after I post the question :s
My SSID is available after 45 seconds, so I will need to increase that value.

**Comment by royfocker19** [comment]
Is this fork up to date? The are some files missing on the components folder. HomeKit version is not the last one

**Pull request closed without merging**
