### PR TITLE
Example Switch

### PR DESCRIPTION
**Pull request by sj-louw**
Add example switch

### CODE REVIEW

**Comment by maximkulkin** [comment]
Although this is a nicely done PR it kind of misses the point: switch is supposed to be something that user physically trigger (switch on/off), it reacts and sends ON characteristic updates. Correct me if I'm wrong. This example is kind of reskinned LED accessory example.

**Comment by sj-louw** [comment]
Maybe I'm misunderstanding. This example is pretty much a reskin of the LED example, in that it shows the switch icon/animation in the homekit IOS app and the device is identified as a switch rather than a light bulb. The switch is, like the LED example, physically triggered by the user (in the homekit IOS app), sending switch characteristic updates rather than light bulb characteristic updates.

The difference is that the GPIO pin number must be changed to a usable GPIO number on the ESP and a relay must be connected here. The relay will then switch when the homekit switch is toggled.

This works for my setup and was my understanding of using this "sketch". Please feel free to delete the pull request, if it's missing the point :)

**Comment by maximkulkin** [comment]
Ok, I it is a legit switch. Although it could be an outlet. Those two indeed have a lot of similarities: both are basically relays and can switch somethings. The difference, however is that light switches are supposed to have a physical switch that user can press and change it's state while outlet just sit there.

So, to make it more idiomatic (since we provide an examples, they supposed to be idiomatic), you need to either incorporate logic of the switch (like implementing a code to handle physical button press and changing switch state in HomeKit and state of relay) or rename it to outlet.

Also, it would be nice to provide a short explanation of what's and why's in source code comment (like it's done in [fireplace example](https://github.com/maximkulkin/esp-homekit-demo/blob/master/examples/fireplace/fireplace.c#L1-L18)), describe what how to wire it with a relay.

**Comment by maximkulkin** [comment]
Recently merged "sonoff_basic" example implements SWITCH service with changes requested here. Closing this one.

**Pull request closed without merging**
