### PR TITLE
Sonoff basic toggle with low pass filtering  

### LINKED ISSUE #70: Random AC interference on sonoff_basic_toggle
Sometimes my kitchens lights get toggled when I turn on some electrical appliances. It doesn't happen every time, but when it happens it was in perfect sync with the mixer or the fridge compressor starting.

I'm testing a solution to debounce based a low pass filter on the switch input to reject noise and using the absolute value of the switch to decides the toggle.

Anyone are having these behaviors too?

### PR DESCRIPTION
**Pull request by pcsaito**
This PR implements a low pass filter on gpio value instead of a time debounce to toggle.

With the default parameters it will filter up to 6 wrong readings and introduces about 60ms delay.

Fixes #70

### CODE REVIEW

**Comment by maximkulkin** [comment]
Can the same thing be done without using tasks (e.g. interrupt handlers + timers) ? Having a task for each toggle is too expensive.

**Comment by pcsaito** [comment]
I think it is.

The only purpose I used a task is to keep a contant update on the LPF values. Anything that executes periodically could do that.

All the toggles could share the same task or interrupt handler if they share the same “refresh” rate.

Is it still preferable to use interrupts instead only one task shared with all toggles?

**Comment by pcsaito** [comment]
I implemented the only-one-task solution.

As the LPF_INTERVAL is a #define, all the toggles already have the same interval, so more than one task never made sense.

If you judge that a interrupt handlers + timers implementation is more adequate I can follow this approach, just used a task because I'm more used to it.

**Comment by maximkulkin** [comment]
Ok, since I do not have bandwidth to do it myself and since it is for this particular example only, I'm fine with current implementation as long as it improves people experiences. Maybe someday somebody will hit this problem and volunteer to improve resource usage (or maybe not).

**Pull request merged**
