### PR TITLE
Create 2-gang ac dimmer

### PR DESCRIPTION
**Pull request by jukorp**
Do you have an example of ac dimming?
Is it possible to make a 2-Gang ac dimmer?

Example hardware:
https://hackaday.io/project/21995-multichannel-wireless-light-dimmer/details

### CODE REVIEW

**Comment by HomeACcessoryKid** [comment]
Please do not use incandescent lamps anymore! Despite Trump denying it, you are ruining the planet!
This is the stuff I build in 1980 (without wifi though ;-)

**Comment by jukorp** [comment]
There are dimmable LED lamps. :) dimming succeeds in the trailing edge.

**Comment by jukorp** [comment]
Can anyone help? 
I can not find any example by ac dimming.
Not pwm. Trailing or leading edge dimming is good.

**Comment by jukorp** [comment]
This is very interesting.
Not yet available. :/

https://deal.koogeek.com/img/logo/0007.png?_ga=2.263184204.1797458001.1516283218-2082207243.1483295862

**Comment by maximkulkin** [comment]
There is no AC dimmer example available but you're more than welcome to contribute.

Basically, first you need a PWM AC dimmer (e.g. [this one](https://www.amazon.com/PWM-AC-Dimmer-Arduino-Raspberry/dp/B076V2RD26/ref=sr_1_1), unless you plan to build it yourself). To control it you need to do PWM (see [this library](https://github.com/SuperHouse/esp-open-rtos/tree/master/extras/pwm)). You start with either [LED example](https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/led) and add Brightness characteristic or [Light bulb example](https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/ZemiSmart) and remove Hue and Saturation from there.

**Comment by HomeACcessoryKid** [comment]
I still discourage the building of equipment that can drive incandescent lamps as well. It means they get not taken out of the loop, which is wrong. So, a dimmer should not (be able to) handle more than 10W of led load.
Save the planet!

**Comment by jukorp** [comment]
the European Union has forbidden the sale of incandescent light bulbs. This is not a problem for us.

There are a lot of people who want dimming.

Triac dimmable lamps are sold in stores.
Eg gu10, e27, e14, downlight, and many more ...

These lamps need a trailing or leading edge dimmer. Trailing is better.

**Comment by jukorp** [comment]
Why did you shut this off?

**Comment by maximkulkin** [comment]
1. This is an issue, not a PR. Nothing to merge here.
2. What do you expect in the end? I pointed to hardware modules and steps on how to implement software.

**Pull request closed without merging**
