### PR TITLE
add blinds/shades example

### PR DESCRIPTION
**Pull request by bowerymarc**
I've created an example controller of two separate blinds (left and right) to add to the examples folder.  It's hardware I created using a [315MHz remote](https://www.mpja.com/Remote-Control-Key-FOB-Receiver-Board-4-Channel/productinfo/32197+MI)  and adapted by adding NodeDev board.  No feedback look - I simply timed the rotation of the motor, so yeah, it's a hack.  But shows how to give positional feedback in homekit, among other things.

### CODE REVIEW

**Comment by maximkulkin** [comment]
Can you please fix conflicts.

**Comment by bowerymarc** [comment]
hmmm... github is showing 'this branch has no conflicts with the base branch' from my end...?

**Comment by maximkulkin** [comment]
I see this: 
screenshot from 2019-03-06 09-39-57

**Comment by bowerymarc** [comment]
ok let me think about it.  this is what I'm seeing 

untitled 2

**Comment by bowerymarc** [comment]
ok, I think I fixed it, I merged the changes since I had cloned this back to my head, do you get conflicts now?  Or maybe I have to close this pull and req a new one?

**Comment by maximkulkin** [comment]
Ok, I figured out how to workaround that problem. Seems like a bug on Github side.

Anyways, merged now. Thank you for contribution!  :+1:

**Comment by bowerymarc** [comment]
Thanks! Did my merging your head back to my branch help?  In any case, I will probably have a couple more coming up in the next few months when I get the time.  Thanks for porting the toolkit, makes this so easy!

**Comment by maximkulkin** [comment]
Merging actually made it worse. Don't do that again. You should rebase instead.

You're more than welcome to contribute more.

**Comment by bowerymarc** [comment]
OK I'll do that next time, thanks!  Had various stack exchange links I was going thru trying to figure this out....

**Comment by skanico** [comment]
Hello!
Thanks for this example.
I wanted to tweak it with physical buttons (using button.c from another example), and I have some questions.
Why is manual time (6400 in your example) different from other times (4300, 5900, 6000, 7000)?
In your example, I noticed that closing time is greater than opening time. In my case, it is the opposite. Is it a mistake? Or the behavior of your blinds is different?
Thanks.

**Comment by bowerymarc** [comment]
Hi!  Glad you like the example.  Those numbers were determined empirically first by timing the blinds, then tweaking them until the blinds behaved themselves - i.e. closed and opened back to the same position.   The manual time is kind of a medium between them…. Based on the mechanical setup, you’ll undoubtedly have to tweak those settings.  Really, some kind of feedback loop or stepper motor should be used but, well what can I say, it’s a hack!  For my blinds it seems the load on the motor is greater one direction than the other, and I wanted to make sure they shut really tightly when closed.  So yeah, allocate some time for tweaking those parameters.
Best,
Marc

**Pull request merged**
