### PR TITLE
WiFi AP

### PR DESCRIPTION
**Pull request by idumzaes**
* When accessory starts, it creates it's own WiFi AP "LED-XXXXXX"
* (where XXXXXX is last 3 digits of accessory's mac address in HEX).
* You will be presented with available WiFi networks to connect to.
* Accessory shuts down AP after successful connection.

### CODE REVIEW

**Comment by maximkulkin** [comment]
Well, a lot of changes is replacing inplace strings with defines and renames which is subjective. Switching to wifi_config library can be done in just 6 lines. I'm OK with wifi_config switch, but changes to strings seem unnecessary to me.

**Comment by idumzaes** [comment]
Fair enough. Wifi_config is much more versatile. Thanks

**Comment by Kristian8606** [comment]
How do I reset the device and connect it to another wifi

**Comment by sakisdog** [comment]
If the associated SSID not found the device starts over creating it's own AP. Then you can select another Wifi AP.

**Comment by idumzaes** [comment]
Hey

**Comment by maximkulkin** [comment]
I personally think that it is easier to try examples with hard coded credentials and not waste time configuring it. When you debug your stuff you will do a lot of flash erasing and thus will have an extra step of configuring WiFi.

**Comment by idumzaes** [comment]
Fair enough.

**Pull request closed without merging**
